Task_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
# from authentications.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('authentications/', include('authentications.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='authentications/login.html', authentication_form=LoginForm,), name='login'),
    
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentications/urls.py
from django.urls import path
from .  import views

app_name = 'authentications'
urlpatterns = [
   
#     path('projectform', views.projectform, name='projectform' ),
    path('register_user/', views.register_user, name='register_user' ),
    path('register_company/', views.register_company, name='register_company' ),
    path('choose_your_group/', views.choose_your_group, name='choose_your_group' ),
    path('signout/', views.signout, name='signout' ),
    # path('userchoice/', views.userchoice, name='userchoice' ),
    path('personal_user_instructions/', views.personal_user_instructions, name='personal_user_instructions' ),
    
    path('loggin', views.loggin, name='loggin' ),
    path('group_leader_instructions', views.group_leader_instructions, name='group_leader_instructions' ),
    path('group_member_instructions', views.group_member_instructions, name='group_member_instructions' ),
    path('editgroup/<int:group_id>/', views.editgroup, name='editgroup' ),    
    
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' ),
    path('projectform/', views.projectform, name='projectform' ),
    path('assigntask/<int:project_id>/', views.assigntask, name='assigntask' ),
    path('deletetask/<int:task_id>/', views.deletetask, name='deletetask' ),
    path('deleteproject/<int:project_id>/', views.deleteproject, name='deleteproject' ),
    path('viewtask/', views.viewtask, name='viewtask' ),
    path('groupdetail/<int:group_id>/', views.groupdetail, name='groupdetail' ),
    path('editproject/<int:project_id>/', views.editproject, name='editproject' ),

]

task/models.py
from django.db import models

from django.conf import settings
from django.contrib.auth import get_user_model
from authentications.models import CustomUser
from django.utils import timezone

class TaskProject(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank = True, null = True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

class Task(models.Model):
    STATUS_CHOICES = [
        ('todo', 'To Do'),
        ('in progress', 'In progress'),
        ('completed', 'Completed'),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(TaskProject, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='todo')
    due_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank = True, null = True, related_name='user')

    def __str__(self):
        return self.title
    
class Statusholder(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank = True, null = True)
    status = models.ForeignKey(Task, on_delete=models.CASCADE)
    
    

task/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from authentications.models import CustomUser
from task.models import Task


class CreatProjectForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter name of project', 'class': 'form-control'
    }))
    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Describe the task', 'class': 'form-control'
    }))
    due_date = forms.CharField(widget=forms.DateInput(attrs={
        'placeholder': 'Due date', 'type': 'date','class': 'form-control'
    }))

class CreateTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'project', 'status', 'assigned_to', 'due_date']
        widgets = {
            'due_date': forms.DateInput(attrs={'type': 'date', 'class':'form-control'}),
        }

task/views.py
from django.shortcuts import render, redirect, get_list_or_404
from . models import Task, TaskProject, Statusholder
from task.forms import CreatProjectForm, CreateTaskForm
from django.contrib import messages
from django.contrib.auth import logout
from task.tasks import send_reminder_emails
from authentications.models import ChooseGroup, CompanyModel, CustomUser

def index(request):
    user = request.user
    projects = TaskProject.objects.filter(user=user)
    tasks = Task.objects.filter(created_by=user)
    assigned_tasks = Task.objects.filter(assigned_to=user)

    if request.method == 'POST':
        task_id = request.POST.get('task_id', None)
        status = request.POST.get('status', None)
        
        if task_id and status in [choice[0] for choice in Task.STATUS_CHOICES]:
            try:
                task = Task.objects.get(id=task_id, assigned_to=user)
                task.status = status
                task.save()
                messages.success(request, 'Task status updated successfully.')
            except Task.DoesNotExist:
                messages.error(request, 'Task not found.')

    context = {
        'tasks': tasks,
        'projects': projects,
        'assigned': assigned_tasks,
    }
    return render(request, 'task/home.html', context)

def viewtask(request):
    user = request.user
    assigned = Task.objects.filter(assigned_to=user)
    assign= assigned.first()

    if request.method == 'POST':
        task_id = request.POST.get('task_id', None)
        status = request.POST.get('status', None)
        if task_id and status in [choice[0] for choice in Task.STATUS_CHOICES]:
            try:
                task = Task.objects.get(id=task_id, assigned_to=user)
                task.status = status
                task.save()
                messages.success(request, 'Task status updated successfully.')
            except Task.DoesNotExist:
                messages.error(request, 'Task not found.')
                
    # assigned_tasks = Task.objects.filter(assigned_to=user) 
    tasks = Task.objects.filter(created_by=user)       
    get_groups = CompanyModel.objects.filter(created_by=user)
    get_all_groups = []
    for group in get_groups:
        members = ChooseGroup.objects.filter(group=group)
        group.members = members
        get_all_groups.append(group)
        
    groupmember = ChooseGroup.objects.filter(user=user)
    

    context = {
        'assigned': assigned,
        'assign':assign,
        'all_groups':get_groups,
        'members':groupmember,
        'tasks':tasks
    }
    return render(request, 'task/dashboard.html', context)



def projectform(request):
    user = request.user
    if request.method == 'POST':
        form = CreatProjectForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            due_date = form.cleaned_data['due_date']
            
            create_project = TaskProject(name = name, description = description, 
                                         due_date=due_date, user=user)
            create_project.save()
            messages.success(request, f'You have add {name} successfully')
            return redirect('index')
        messages.error(request, 'Project not save')
        return redirect('projectform')
    form = CreatProjectForm()
    context = {
        'form':form,
    }
    return render(request, 'task/create_project.html', context)

def editproject(request, project_id):
    user = request.user
    projectid = TaskProject.objects.get(id = project_id)
    if request.method == 'POST':
        
        form = CreatProjectForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            due_date = form.cleaned_data['due_date']
            
            projectid.name=name
            projectid.description=description
            projectid.due_date =due_date
            projectid.user = user
            
            projectid.save()
           
            messages.success(request, f'You have updated {name} successfully')
            return redirect('index')
        messages.error(request, 'Project not save')
        return redirect('projectform')
    initial_data={
        'name':projectid.name,
        'description':projectid.description,
        'due_date':projectid.due_date,
    }
    form = CreatProjectForm(initial=initial_data)
    context = {
        'form':form,
    }
    return render(request, 'task/edit_project.html', context)

 
def assigntask(request, project_id):
    user = request.user
    project = TaskProject.objects.get(id=project_id)
    customusers = ChooseGroup.objects.filter(user=project.user)
    # send_reminder_emails.apply_async(countdown=60)
    
    if request.method == 'POST':
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            assign_to = form.cleaned_data['assigned_to']
            task = form.save(commit=False)
            task.project = project
            task.assigned_to = assign_to
            task.created_by = user
            task.save()
            messages.success(request, 'You assigned a task successfully')
            return redirect('assigntask', project.id)

        else:
            messages.error(request, 'Form is not valid. Please check the errors.')
    else:
        initial_data = {
            'title': project.name,
            'description': project.description,
            'project': project
            
        }
        form = CreateTaskForm(initial=initial_data)
        # ass_task = project.task_set.all()
        form.fields['assigned_to'].queryset = CustomUser.objects.filter(choosegroup__group__created_by=project.user)

        form.fields['project'].queryset = TaskProject.objects.filter(user=user)

    context = {
        'form': form,
        'project': project,
    }
    return render(request, 'task/assignproject.html', context)
       
def deletetask(request, task_id):
    task_id = Task.objects.get(id = task_id)
    task_id.delete()
    messages.info(request, 'deleted!')
    
    return redirect('index')

def deleteproject(request, project_id):
    project_id = TaskProject.objects.get(id = project_id)
    project_id.delete()
    messages.info(request, 'deleted!')
    
    return redirect('index')

def groupdetail(request, group_id):
    group =  CompanyModel.objects.get(id=group_id)
    context = {
        'groups':group,
    }
    return render(request, 'task/group_details.html', context)

task/templates/task/assignproject.html
{% extends 'task/navigations/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="col-sm-12 col-md-8 container mt-4 bg-light">
    <h1>Assign Project</h1>
    <hr>
    {% for message in messages %}
    <div class="text-center text-danger">{{ message }}</div>
    {% endfor %}
    <form method="POST" action="{% url 'assigntask' project.id %}" class="mt-4">
        {% csrf_token %}
        
        <div class="form-group shadow p-3 mb-5 bg-dark text-white rounded">
            <label for="id_title"></label>
            {{ form.title|as_crispy_field }}
        </div>
        
        <div class="form-group shadow p-3 mb-5 bg-dark text-white rounded">
            <label for="id_description"></label>
            {{ form.description|as_crispy_field }}
        </div>
        <div class="form-group shadow p-3 mb-5 bg-dark text-white rounded">
            <label for="id_assigned_to"></label>
            {{ form.project|as_crispy_field }}
        </div>
        
        <div class="form-group shadow p-3 mb-5 bg-dark text-white rounded">
            <label for="id_status"></label>
            {{ form.status|as_crispy_field }}
        </div>
        
        <div class="form-group shadow p-3 mb-5 bg-dark text-white rounded">
            <label for="id_assigned_to"></label>
            {{ form.assigned_to|as_crispy_field }}
        </div>
        
        <div class="form-group shadow p-3 mb-5 bg-dark text-white rounded">
            <label for="id_due_date"></label>
            {{ form.due_date|as_crispy_field }}
        </div>
        
        <button type="submit" class="col-md-12 btn btn-primary  mb-5">Create</button>
    </form>
</div>
{% endblock %}

task/templates/task/create_project.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="col-sm-12 col-md-8 container mt-4">
<h1>Create Project</h1>
<hr>
<form method="POST" action="{% url 'projectform' %}">
    {% csrf_token %}
    <div class="mb-3">
    <label for="id_name" class="form-label"></label>
    {{ form.name }}
    </div>
    <div class="mb-3">
    <label for="id_description" class="form-label"></label>
    {{ form.description }}
    </div>
    <div class="mb-3">
        <label for="id_description" class="form-label"></label>
        {{ form.due_date }}
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>
</div>
{% endblock %}

task/templates/task/dashboard.html
{% extends 'task/navigations/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Task Page{% endblock %}

{% block content %}

<!-- assigned project user -->
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
  <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
  <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management System</h2>
  <p class="lead" style="color: #6c757d;">Your Dashboard</p>
</div>

{% if user.is_group_leader or user.is_staff %}
<div class="container">
  <div class="row">
    <div class="col-md-4 col-sm-12 mx-auto">
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">My Groups with the Participants</h2>
          {% for group in all_groups %}
            <p class="card-text text-danger">Group: {{ group.name }}</p>
            <div class="container">
              {% for member in group.members.all %}
                <div class="lead text-start">{{ member.user }}</div>
              {% endfor %}
            </div>
            <div class="row justify-content-center">
              <div class="col-md-6 mx-auto">
                <a href="{% url 'groupdetail' group.id %}" class="btn btn-secondary btn-block"> View Details</a>
              </div>
              <div class="col-md-6 mx-auto">
                <a href="{% url 'authentications:editgroup' group.id %}" class="btn btn-secondary btn-block"> Edit Group</a>
              </div>

            </div>
            
          {% empty %}
            <p class="card-text">You are not a member of any groups.</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
<!-- people you asssign project to -->
<div class="col-sm-12 col-md-10 col-lg-10 mx-auto pt-5">
  {% if tasks %}
  <h4 class="col-md-6 btn mb-3 mx-auto" style="font-size: 1.5rem;">People you assigned Project to</h4>

  
  <table class="table table-striped table-dark mb-5">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Project</th>
        <th scope="col">Description</th>
        <th scope="col">Create_date</th>
        <th scope="col">Due date</th>
        <th scope="col">Status</th>
        <th scope="col">Assign to</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
      <tr>
        <th scope="row">{{ forloop.counter}}</th>
        <td>{{ task.title }}</td>
        <td>{{ task.description }}</td>
        <td>{{ task.created_at }}</td>
        <td>{{ task.due_date }}</td>
        <td>{{ task.status }}</td>
        <td>{{ task.assigned_to}}</td>
        
        <td><a href="{% url 'deletetask' task.id %}" class=" btn-secondary mb-3">delete</a></td>
      </tr>
      <tr>
          
      {% endfor %}
        
    </tbody>
  </table>
  {% else %}
  <div class="text-center mb-5 text-white bg-dark">
    <p>You did not assign task yet.</p>
  </div>
  {% endif %}
  
                
</div>
<!-- end -->
{% else %}
<div class="container">
  <div class="row">
    <div class="col-md-4 col-sm-12 mx-auto">
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title">Groups i Belong</h2>
          {% for group in members %}
            <p class="card-text text-danger">Group: {{ group.group.name }}</p>
            <div class="container">
                <small class="lead text-start">Created by: {{ group.group.created_by }} | {{ group.group.date_created|date }}</small>
            </div>
            <div class="row justify-content-center">
              <div class="col-md-6 mx-auto">
                <a href="{% url 'groupdetail' group.id %}" class="btn btn-secondary btn-block"> View Details</a>
              </div>
              <div class="col-md-6 mx-auto">
                <a href="{% url 'authentications:editgroup' group.id %}" class="btn btn-secondary btn-block"> Edit Group</a>
              </div>

            </div>
          {% empty %}
            <p class="card-text">You are not a member of any groups.</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 mx-auto">
      <div class="card mx-auto" style="width: 600px;">
        <div class="card-body">
          <h2 class="card-title">Assigned Projects</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Description</th>
                  <th scope="col">Created Date</th>
                  <th scope="col">Status</th>
                  <th scope="col">Assigned By</th>
                  <th scope="col">Due Date</th>
                </tr>
              </thead>
              <tbody>
                {% for project in assigned %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ project.title }}</td>
                    <td>{{ project.description }}</td>
                    <td>{{ project.created_at }}</td>
                    <td>
                      <form id="status-form" method="POST" action=".">
                        {% csrf_token %}
                        <input type="hidden" name="task_id" value="{{ project.id }}">
                        <div class="btn-group" role="group">
                          <button type="submit" name="status" value="todo" class="btn btn-primary">To Do</button>
                          <button type="submit" name="status" value="in progress" class="btn btn-primary">In Progress</button>
                          <button type="submit" name="status" value="completed" class="btn btn-primary">Completed</button>
                        </div>
                      </form>
                    </td>
                    <td>{{ project.created_by }}</td>
                    <td>{{ project.due_date }}</td>
                  </tr>
                {% empty %}
                  <tr>
                    <td colspan="7">No assigned projects.</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="shadow shadow-dark mb-5">
  {% for message in messages %}
    <div class="text-center text-danger mb-5">{{ message }}</div>
  {% endfor %}
</div>

{% endif %}


{% endblock %}

task/templates/task/edit_project.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="col-sm-12 col-md-8 container mt-4">
<h1>Edit Project</h1>
<hr>
<form method="POST" action=".">
    {% csrf_token %}
    <div class="mb-3">
    <label for="id_name" class="form-label"></label>
    {{ form.name }}
    </div>
    <div class="mb-3">
    <label for="id_description" class="form-label"></label>
    {{ form.description }}
    </div>
    <div class="mb-3">
        <label for="id_description" class="form-label"></label>
        {{ form.due_date }}
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>
</div>
{% endblock %}

task/templates/task/group_details.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
    <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
    <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management Systme</h2>
    <p class="lead" style="color: #6c757d;">Add and check your task here</p>
</div>
  
<div class="container">
    <div class="card col-md-10">
        <div class="card-body">
            <h2 class="card-title">{{ groups.name }}</h2>
            <p class="card-text">Moto:{{ groups.moto }}</p>
            <div class="row justify-content-center">
                <img src="{{ groups.image.url }}" alt="groups image" class="img-thumbnails" style="width: 400px; height: auto;">
                <p class="card-text">Description: {{ groups.description }}</p>

                <div class="col-md-6">
                    <a href="{% url 'viewtask' %}" class="btn btn-primary btn-block">Back to dashbord</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'index' %}" class="btn btn-secondary btn-block">Go to todo</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task/templates/task/home.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
  <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
  <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management Systme</h2>
  <p class="lead" style="color: #6c757d;">Add and check your task here</p>
</div>
<div class="pt-5">
  {% for message in messages %}
    <div class="text-center text-danger">{{ message }}</div>
  {% endfor %}
  <div class="shadow shadow-dark">
    <div class="col-sm-12 col-md-10 col-lg-10 mx-auto">
      <a href="{% url 'projectform' %}" class="col-md-6 btn btn-secondary mb-3">Create Task</a>

      
      <table class="table table-striped table-dark table-responsive">
        {% if user.is_group_leader or user.is_staff %} 
        {% if projects %}
        
        <thead>
          <tr>
            
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Create_date</th>
            <th scope="col">Status</th>
            <th scope="col">Assign Project</th>
            <th scope="col">Due Date</th>

          </tr>
        </thead>

        <tbody>
          
          {% for project in projects %}
          <tr>
            <th scope="row">{{ forloop.counter}}</th>
            <td>{{ project.name }}</td>
            <td>{{ project.description }}</td>
            <td>{{ project.created_at }}</td>
            <td>@mdo</td>
            <td><a href="{% url 'assigntask' project.id %}" class=" btn-secondary mb-3">Assign Task</a></td>
            <td><a href="{% url 'deleteproject' project.id %}" class=" btn-secondary mb-3">delete project</a></td>
            <td><a href="{% url 'editproject' project.id %}" class=" btn-secondary mb-3">edit</a></td>
            
          </tr>
          <tr>
            
          {% endfor %}
           
        </tbody>
        {% else %}
          <div class="text-center bg-dark text-white lead">
            You did not create task yet
          </div>
        {% endif %} 
      <!-- for personal user -->
      {% else %}
      {% if projects %}
      <thead>
        <tr>
          
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Create_date</th> 
          <th scope="col">Due Date</th>

        </tr>
      </thead>

      <tbody>
        
        {% for project in projects %}
        <tr>
          <th scope="row">{{ forloop.counter}}</th>
          <td>{{ project.name }}</td>
          <td>{{ project.description }}</td>
          <td>{{ project.created_at }}</td>
          <td>{{ project.due_date }}</td>
          
          
          
          <td><a href="{% url 'deleteproject' project.id %}" class=" btn-secondary mb-3">delete project</a></td>
          <td><a href="{% url 'editproject' project.id %}" class=" btn-secondary mb-3">edit</a></td>
            
        </tr>
        <tr>
          
        {% endfor %}
         
      </tbody>
      {% else %}
        <div class="text-center bg-dark text-white lead">
          You did not create task yet
        </div>
      {% endif %} 
      {% endif %} 
      
      
      </table>
      
  
    </div>
  
    
  </div>
  <hr>

  <!-- assigned project user -->
  {% if user.is_group_leader or user.is_group_member or user.is_staff %}
  <div class="shadow shadow-dark mb-5">
    <div class="col-sm-12 col-md-10 col-lg-10 mx-auto">
      <h4 class="col-md-6 btn mb-3 mx-auto" style="font-size: 1.5rem;">Project you have been assign to</h4>     
      <table class="table table-striped table-info table-responsive">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Create_date</th>
            <th scope="col">Status</th>
            <th scope="col">Assigned by</th>
            <th scope="col">Due date</th>

          </tr>
        </thead>
        <tbody>
          {% for project in assigned %}
          <tr>
            <th scope="row">{{ forloop.counter}}</th>
            <td>{{ project.title }}</td>
            <td>{{ project.description }}</td>
            <td>{{ project.created_at }}</td>
            <td>
              <form id="status-form" method="POST" action=".">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="{{ project.id }}">
                <!-- <input type="submit" name="upload" class="btn btn-primary" value="Upload" {% if not enable %}disabled {%endif%} /> -->
                <button type="submit" name="status" value="todo">To Do</button>
                <button type="submit" name="status" value="in progress" >In Progress</button>
                <button type="submit" name="status" value="completed" >Completed</button>
              </form>
            
            </td>
            <td>{{ project.created_by }}</td>
            <td>{{ project.due_date }}</td>
            
          </tr>
          <tr>
          {% endfor %}
            
        </tbody>
      </table>
  
    </div>
  <!-- end -->
  <hr>
    <div class="col-sm-12 col-md-10 col-lg-10 mx-auto pt-5">
      {% if tasks %}
      <h4 class="col-md-6 btn mb-3 mx-auto" style="font-size: 1.5rem;">People you assigned Project to</h4>

      
      <table class="table table-striped table-dark mb-5 table-responsive">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Project</th>
            <th scope="col">Description</th>
            <th scope="col">Create_date</th>
            <th scope="col">Due date</th>
            <th scope="col">Status</th>
            <th scope="col">Assign to</th>
          </tr>
        </thead>
        <tbody>
          {% for task in tasks %}
          <tr>
            <th scope="row">{{ forloop.counter}}</th>
            <td>{{ task.title }}</td>
            <td>{{ task.description }}</td>
            <td>{{ task.created_at }}</td>
            <td>{{ task.due_date }}</td>
            <td>{{ task.status }}</td>
            <td>{{ task.assigned_to}}</td>
            
            <td><a href="{% url 'deletetask' task.id %}" class=" btn-secondary mb-3">delete</a></td>
          </tr>
          <tr>
          {% endfor %}
            
        </tbody>
      </table>
      {% endif %}
    </div>

  {% endif %}
    
  </div>
  </div>

  {% endblock %}

  