Task_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
# from authentications.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('authentications/', include('authentications.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='authentications/login.html', authentication_form=LoginForm,), name='login'),
    
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentications/urls.py
from django.urls import path
from .  import views

app_name = 'authentications'
urlpatterns = [
   
#     path('projectform', views.projectform, name='projectform' ),
    path('register_user/', views.register_user, name='register_user' ),
    path('register_company/', views.register_company, name='register_company' ),
    path('choose_your_group/', views.choose_your_group, name='choose_your_group' ),
    path('signout/', views.signout, name='signout' ),
    # path('userchoice/', views.userchoice, name='userchoice' ),
    path('personal_user_instructions/', views.personal_user_instructions, name='personal_user_instructions' ),
    
    path('loggin', views.loggin, name='loggin' ),
    path('group_leader_instructions', views.group_leader_instructions, name='group_leader_instructions' ),
    path('group_member_instructions', views.group_member_instructions, name='group_member_instructions' ),
    path('editgroup/<int:group_id>/', views.editgroup, name='editgroup' ),    
    
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' ),
    path('projectform/', views.projectform, name='projectform' ),
    path('assigntask/<int:project_id>/', views.assigntask, name='assigntask' ),
    path('deletetask/<int:task_id>/', views.deletetask, name='deletetask' ),
    path('deleteproject/<int:project_id>/', views.deleteproject, name='deleteproject' ),
    path('viewtask/', views.viewtask, name='viewtask' ),
    path('groupdetail/<int:group_id>/', views.groupdetail, name='groupdetail' ),
    path('editproject/<int:project_id>/', views.editproject, name='editproject' ),

]

task/models.py
from django.db import models

from django.conf import settings
from django.contrib.auth import get_user_model
from authentications.models import CustomUser
from django.utils import timezone

class TaskProject(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank = True, null = True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

class Task(models.Model):
    STATUS_CHOICES = [
        ('todo', 'To Do'),
        ('in progress', 'In progress'),
        ('completed', 'Completed'),
    ]

    title = models.CharField(max_length=100)
    description = models.TextField()
    project = models.ForeignKey(TaskProject, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='todo')
    due_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank = True, null = True, related_name='user')

    def __str__(self):
        return self.title
    
class Statusholder(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank = True, null = True)
    status = models.ForeignKey(Task, on_delete=models.CASCADE)
    
    

task/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from authentications.models import CustomUser
from task.models import Task


class CreatProjectForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter name of project', 'class': 'form-control'
    }))
    description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Describe the task', 'class': 'form-control'
    }))
    due_date = forms.CharField(widget=forms.DateInput(attrs={
        'placeholder': 'Due date', 'type': 'date','class': 'form-control'
    }))

class CreateTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'project', 'status', 'assigned_to', 'due_date']
        widgets = {
            'due_date': forms.DateInput(attrs={'type': 'date', 'class':'form-control'}),
        }

task/views.py
from django.shortcuts import render, redirect, get_list_or_404
from . models import Task, TaskProject, Statusholder
from task.forms import CreatProjectForm, CreateTaskForm
from django.contrib import messages
from django.contrib.auth import logout
from task.tasks import send_reminder_emails
from authentications.models import ChooseGroup, CompanyModel, CustomUser

def index(request):
    user = request.user
    projects = TaskProject.objects.filter(user=user)
    tasks = Task.objects.filter(created_by=user)
    assigned_tasks = Task.objects.filter(assigned_to=user)

    if request.method == 'POST':
        task_id = request.POST.get('task_id', None)
        status = request.POST.get('status', None)
        
        if task_id and status in [choice[0] for choice in Task.STATUS_CHOICES]:
            try:
                task = Task.objects.get(id=task_id, assigned_to=user)
                task.status = status
                task.save()
                messages.success(request, 'Task status updated successfully.')
            except Task.DoesNotExist:
                messages.error(request, 'Task not found.')

    context = {
        'tasks': tasks,
        'projects': projects,
        'assigned': assigned_tasks,
    }
    return render(request, 'task/home.html', context)

def viewtask(request):
    user = request.user
    assigned = Task.objects.filter(assigned_to=user)
    assign= assigned.first()

    if request.method == 'POST':
        task_id = request.POST.get('task_id', None)
        status = request.POST.get('status', None)
        if task_id and status in [choice[0] for choice in Task.STATUS_CHOICES]:
            try:
                task = Task.objects.get(id=task_id, assigned_to=user)
                task.status = status
                task.save()
                messages.success(request, 'Task status updated successfully.')
            except Task.DoesNotExist:
                messages.error(request, 'Task not found.')
                
    # assigned_tasks = Task.objects.filter(assigned_to=user) 
    tasks = Task.objects.filter(created_by=user)       
    get_groups = CompanyModel.objects.filter(created_by=user)
    get_all_groups = []
    for group in get_groups:
        members = ChooseGroup.objects.filter(group=group)
        group.members = members
        get_all_groups.append(group)
        
    groupmember = ChooseGroup.objects.filter(user=user)
    

    context = {
        'assigned': assigned,
        'assign':assign,
        'all_groups':get_groups,
        'members':groupmember,
        'tasks':tasks
    }
    return render(request, 'task/dashboard.html', context)



def projectform(request):
    user = request.user
    if request.method == 'POST':
        form = CreatProjectForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            due_date = form.cleaned_data['due_date']
            
            create_project = TaskProject(name = name, description = description, 
                                         due_date=due_date, user=user)
            create_project.save()
            messages.success(request, f'You have add {name} successfully')
            return redirect('index')
        messages.error(request, 'Project not save')
        return redirect('projectform')
    form = CreatProjectForm()
    context = {
        'form':form,
    }
    return render(request, 'task/create_project.html', context)

def editproject(request, project_id):
    user = request.user
    projectid = TaskProject.objects.get(id = project_id)
    if request.method == 'POST':
        
        form = CreatProjectForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            due_date = form.cleaned_data['due_date']
            
            projectid.name=name
            projectid.description=description
            projectid.due_date =due_date
            projectid.user = user
            
            projectid.save()
           
            messages.success(request, f'You have updated {name} successfully')
            return redirect('index')
        messages.error(request, 'Project not save')
        return redirect('projectform')
    initial_data={
        'name':projectid.name,
        'description':projectid.description,
        'due_date':projectid.due_date,
    }
    form = CreatProjectForm(initial=initial_data)
    context = {
        'form':form,
    }
    return render(request, 'task/edit_project.html', context)

 
def assigntask(request, project_id):
    user = request.user
    project = TaskProject.objects.get(id=project_id)
    customusers = ChooseGroup.objects.filter(user=project.user)
    # send_reminder_emails.apply_async(countdown=60)
    
    if request.method == 'POST':
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            assign_to = form.cleaned_data['assigned_to']
            task = form.save(commit=False)
            task.project = project
            task.assigned_to = assign_to
            task.created_by = user
            task.save()
            messages.success(request, 'You assigned a task successfully')
            return redirect('assigntask', project.id)

        else:
            messages.error(request, 'Form is not valid. Please check the errors.')
    else:
        initial_data = {
            'title': project.name,
            'description': project.description,
            'project': project
            
        }
        form = CreateTaskForm(initial=initial_data)
        # ass_task = project.task_set.all()
        form.fields['assigned_to'].queryset = CustomUser.objects.filter(choosegroup__group__created_by=project.user)

        form.fields['project'].queryset = TaskProject.objects.filter(user=user)

    context = {
        'form': form,
        'project': project,
    }
    return render(request, 'task/assignproject.html', context)
       
def deletetask(request, task_id):
    task_id = Task.objects.get(id = task_id)
    task_id.delete()
    messages.info(request, 'deleted!')
    
    return redirect('index')

def deleteproject(request, project_id):
    project_id = TaskProject.objects.get(id = project_id)
    project_id.delete()
    messages.info(request, 'deleted!')
    
    return redirect('index')

def groupdetail(request, group_id):
    group =  CompanyModel.objects.get(id=group_id)
    context = {
        'groups':group,
    }
    return render(request, 'task/group_details.html', context)

task/templates/task/navigations/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Task Management System{% block title %}{% endblock %}</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

  <style>
    .card {
        margin-top: 100px;
        width: 400px;
        margin-left: auto;
        margin-right: auto;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    }
    .card-body {
        padding: 20px;
        text-align: center;
    }
</style>
  <script>
    function updateStatus(nextStatus) {
        const buttons = document.querySelectorAll('#status-form button');
        buttons.forEach((button) => {
            button.disabled = true;
        });

        const nextButton = document.querySelector(`#status-form [value="${nextStatus}"]`);
        if (nextButton) {
            nextButton.disabled = false;
        }

        document.querySelector('#status-form [name="status"]').value = nextStatus;
    }

    // Enable the "To Do" button initially
    const todoButton = document.querySelector('#status-form [value="todo"]');
    if (todoButton) {
        todoButton.disabled = false;
    }
</script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Task Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link bg-info text-white" href="{% url 'viewtask' %}">Helo {{user.username}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'projectform' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'viewtask' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'authentications:signout' %}">Logout</a>
          </li>
        </ul>
      </div>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'authentications:loggin' %}">Signin</a>
      </li>
      {% endif %}
    </div>
  </nav>

  <div class="container mt-4 mx-auto">
    {% block content %}

  {% endblock %}
    
  </div>
  

  <!-- Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>