Task_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
# from authentications.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('authentications/', include('authentications.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='authentications/login.html', authentication_form=LoginForm,), name='login'),
    
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentications/urls.py
from django.urls import path
from .  import views

app_name = 'authentications'
urlpatterns = [
   
#     path('projectform', views.projectform, name='projectform' ),
    path('register_user/', views.register_user, name='register_user' ),
    path('register_company/', views.register_company, name='register_company' ),
    path('choose_your_group/', views.choose_your_group, name='choose_your_group' ),
    path('signout/', views.signout, name='signout' ),
    # path('userchoice/', views.userchoice, name='userchoice' ),
    path('personal_user_instructions/', views.personal_user_instructions, name='personal_user_instructions' ),
    
    path('loggin', views.loggin, name='loggin' ),
    path('group_leader_instructions', views.group_leader_instructions, name='group_leader_instructions' ),
    path('group_member_instructions', views.group_member_instructions, name='group_member_instructions' ),
    path('editgroup/<int:group_id>/', views.editgroup, name='editgroup' ),    
    
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' ),
    path('projectform/', views.projectform, name='projectform' ),
    path('assigntask/<int:project_id>/', views.assigntask, name='assigntask' ),
    path('deletetask/<int:task_id>/', views.deletetask, name='deletetask' ),
    path('deleteproject/<int:project_id>/', views.deleteproject, name='deleteproject' ),
    path('viewtask/', views.viewtask, name='viewtask' ),
    path('groupdetail/<int:group_id>/', views.groupdetail, name='groupdetail' ),
    path('editproject/<int:project_id>/', views.editproject, name='editproject' ),

]

authentications/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission


# Create your models here.
class CompanyModel(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    moto = models.CharField(max_length=255, blank=False, null=False)
    description = models.CharField(max_length=500, blank=False, null=False)
    date_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('CustomUser', on_delete=models.CASCADE, blank = True, null = True)
    image = models.ImageField(upload_to='media', null = True, blank=True)
    def __str__(self):
        return self.name
    
class ChooseGroup(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE, blank = True, null = True)
    group = models.ForeignKey(CompanyModel, on_delete=models.CASCADE, blank=False)
    
    def __str__(self):
        return self.group.name
    
class CustomUser(AbstractUser):
    is_personal = models.BooleanField('For personal use', default = False )
    is_group_leader = models.BooleanField('Group Leader', default = False )
    is_group_member=models.BooleanField('Group Member', default = False )
    group = models.ForeignKey(CompanyModel, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta(AbstractUser.Meta):
        swappable = 'authentications.CustomUser'
    
        # app_label = 'authentications'
    
    def __str__(self):
        return self.username
    

CustomUser.groups.field.remote_field.related_name = 'customuser_set'
CustomUser.user_permissions.field.remote_field.related_name = 'customuser_permissions_set'
# PersonalUser.groups.field.remote_field.related_name = 'personaluser_set'
# PersonalUser.user_permissions.field.remote_field.related_name = 'personaluser_permissions_set'

authentications/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth.forms import AuthenticationForm
from authentications.models import CustomUser
from authentications.models import CompanyModel, ChooseGroup
from django.core.exceptions import ValidationError

from django.contrib.auth import get_user_model
from django.forms import ClearableFileInput

CustomUser = get_user_model()



class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)


    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 
                  'password2', 'is_personal', 
                  'is_group_leader', 'is_group_member' ]

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match. Please try again.")
        if CustomUser.objects.filter(username = username).exists():
            raise forms.ValidationError("Username already exist")
        if CustomUser.objects.filter(email = email).exists():
            raise forms.ValidationError("Email already exist")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': ''
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': ''
    }))

    class Meta:
        fields = ['username', 'password']
        
class CompanyRegistrationForm(forms.ModelForm):
    image = forms.ImageField(widget=ClearableFileInput)

    class Meta:
        model = CompanyModel
        fields = ['name', 'description', 'moto', 'image']
        
class GroupSelectionForm(forms.ModelForm):
    class Meta:
        model = ChooseGroup
        fields = ['group',]

authentications/views.py
from django.shortcuts import render, redirect
from authentications.forms import *
from authentications.models import CustomUser, ChooseGroup
from django.contrib import messages
 
from django.contrib.auth import authenticate, login,logout


def register_user(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            
            user = form.save()
            user.save()
            return redirect('authentications:loggin')
    else:
        form = UserRegistrationForm()
    return render(request, 'authentications/signup.html', {'form': form})


def loggin(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_group_leader or user.is_staff:
                login(request, user)
                messages.info(request, 'Login successful')
                return redirect('authentications:group_leader_instructions')
            elif user is not None and user.is_group_member:
                login(request, user)
                messages.info(request, 'Login successful')
                return redirect('authentications:group_member_instructions')
            elif user is not None and user.is_personal:
                login(request, user)
                messages.info(request, 'Login successful')
                return redirect('authentications:personal_user_instructions')
            
            messages.info(request, 'Invalid data')
            return redirect('authentications:loggin')
    else:
        form = LoginForm(request)
    return render(request, 'authentications/login.html', {'form': form})

def register_company(request):
    user=request.user
    if request.method == 'POST':
        form = CompanyRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            save_group= form.save(commit = False)
            save_group.created_by=user
            save_group.save()
            
            return redirect('index')
    else:
        form = CompanyRegistrationForm()
    return render(request, 'authentications/companyform.html', {'form': form})

def editgroup(request, group_id):
    group = CompanyModel.objects.get(id=group_id)
    user = request.user
    if request.method == 'POST':
        form = CompanyRegistrationForm(request.POST, request.FILES, instance=group)
        if form.is_valid():
            
            save_group = form.save(commit=False)
            save_group.created_by = user
            save_group.save()
            return redirect('index')
   
       
    form = CompanyRegistrationForm(instance=group)
    return render(request, 'authentications/edit_group.html', {'form': form})



def choose_your_group(request):
    user = request.user
    if request.method == 'POST':
        form = GroupSelectionForm(request.POST)
        if form.is_valid():
            if user.is_group_member:
                group = form.cleaned_data['group']
                ChooseGroup.objects.get_or_create(group = group, user = user)
                messages.info(request, f'{group} choosed!!!')
                return redirect('index')
            messages.error(request, 'You dont belong to any group.')
            return redirect('index')
        form.save()
        messages.success(request, f'{group} added register successful')
        return redirect('index')
    form = GroupSelectionForm()
    context ={
        'form':form
    }
    return render(request, 'authentications/choosegroupform.html', context)
           

def signout(request):
    logout(request)
    messages.info(request, 'You just logged out, login again!')
    return redirect('authentications:loggin')


def personal_user_instructions(request):
    return render(request, 'authentications/personal_user_instruction.html', {})

def group_leader_instructions(request):
    return render(request, 'authentications/group_leader_instruction.html', {})

def group_member_instructions(request):
    return render(request, 'authentications/group_members.html', {})

# def list_of_people_in_group(request, group_id):
    
    

authentications/templates/authentications/choosegroupform.html
{% extends 'task/navigations/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Home Page{% endblock %}

{% block content %}
    
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
    <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
    <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management Systme</h2>
    <p class="lead" style="color: #6c757d;">Add and check your task here</p>
</div>
  
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Welcome to Task Management System</h2>
            <p class="card-text">Are you here for personal use or for your company?</p>

            <form method="POST" action="{% url 'authentications:choose_your_group' %}">
                
                {% csrf_token %}
                <div class="form-group col-md-10 mx-auto">
                    <div class="text-success mx-auto">
                        {% for msgs in messages %}
                        <span>
                            {{ msgs }}
                        </span>
                        {% endfor %}
                    </div>
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control mb-3">
                        {{ form.group|as_crispy_field }}
                    </div>  
    
                </div>
                
                <div class="form-group col-md-10 mx-auto mb-3">                    
                    {% if form.errors %}
                        <div class="alert alert-danger ">
                            <strong>Error:</strong> {{ form.non_field_errors.0 }}
                        </div>
                    {% endif %}
                    <button type="submit" class="btn btn-success">Save group</button>
                    
                </div>
            </form>
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <a href="{% url 'index' %}" class="btn btn-primary btn-block">View Task</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'viewtask' %}" class="btn btn-secondary btn-block">Dashbord</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

authentications/templates/authentications/companyform.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="col-sm-12 col-md-8 container mt-4">
    <h1>Register your company</h1>
    <hr>
    <form method="POST" action="{% url 'authentications:register_company' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label"></label>
            <input type="text" class="form-control" id="id_name" name="{{ form.name.name }}" placeholder="Enter company name">
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label"></label>
            <input type="text" class="form-control" id="id_description" name="{{ form.description.name }}" placeholder="Describe you company">
        </div>
        
        <div class="mb-3">
            <label for="id_moto" class="form-label"></label>
            <input type="text" class="form-control" id="id_moto" name="{{ form.moto.name }}" placeholder="Moto of your company">
        </div>
        <div class="mb-3">
            <label for="id_image" class="form-label"></label>
            <input type="file" class="form-control" id="id_image" name="{{ form.image.name }}" placeholder="Moto of your company">
        </div>
        
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

{% endblock %}

authentications/templates/authentications/edit_group.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="col-sm-12 col-md-8 container mt-4">
    <h1>Edit Your Group</h1>
    <hr>
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Company Name</label>
            <input type="text" class="form-control" id="id_name" value="{{ form.instance.name }}" name="{{ form.name.name }}" placeholder="Enter company name">
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            <input type="text" class="form-control" id="id_description" value="{{ form.instance.description }}" name="{{ form.description.name }}" placeholder="Describe your company">
        </div>
        
        <div class="mb-3">
            <label for="id_moto" class="form-label">Moto</label>
            <input type="text" class="form-control" id="id_moto" value="{{ form.instance.moto }}" name="{{ form.moto.name }}" placeholder="Moto of your company">
        </div>
        <div class="mb-3">
            <label for="id_image" class="form-label">Image</label>
            <input type="file" class="form-control" id="id_image" name="{{ form.image.name }}">
        </div>
        
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>

{% endblock %}

authentications/templates/authentications/group_leader_instruction.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
    <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
    <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management Systme</h2>
    <p class="lead" style="color: #6c757d;">Add and check your task here</p>
</div>
  
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Welcome to Task Management System</h2>
            <p class="card-text">Are you here for personal use or for your company?</p>
            <div class="row justify-content-center">
                <p>
                    Hello, group lead! As a leader, you have additional capabilities to manage projects and assign tasks to group members.
                    Login to your account using your username and password on the login page.
                    Once logged in, you will be redirected to your group lead dashboard.
                    From the dashboard, you can create a group by providing a group name and inviting members to sign up for the Task Management System.
                    After your group members have signed up, you can create projects and assign tasks to specific group members.
                    To create a project, navigate to the "Projects" section and click on the "Create Project" button.
                    Specify the project details such as name, description, and due date.
                    Once the project is created, you can assign tasks to group members by selecting the project and choosing the member to assign the task to.
                    The assigned tasks will appear in the respective group members' dashboards.
                </p>
                <div class="col-md-6">
                    <a href="{% url 'projectform' %}" class="btn btn-primary btn-block">Create project</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'authentications:register_company' %}" class="btn btn-secondary btn-block">Create Group</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

authentications/templates/authentications/group_members.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
    <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
    <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management Systme</h2>
    <p class="lead" style="color: #6c757d;">Add and check your task here</p>
</div>
  
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Welcome to Task Management System</h2>
            <p class="card-text">Are you here for personal use or for your company?</p>
            <div class="row justify-content-center">
                <p>
                    Welcome, group member! As a member of a group, you will receive task assignments and can keep track of your to-do list.
Login to your account using your username and password on the login page.
Once logged in, you will be redirected to your group member dashboard.
From the dashboard, you can view the tasks assigned to you by the group lead.
Additionally, you can create your own to-do list or check your email for any task assignments sent by the group lead.
To create a personal to-do item, click on the "Add To-Do" button and provide the task details such as name, description, and due date.
Use the dashboard to manage and update your personal to-do list.
                </p>
                <div class="col-md-6">
                    <a href="{% url 'viewtask' %}" class="btn btn-primary btn-block">View your task</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'authentications:choose_your_group' %}" class="btn btn-secondary btn-block">Choose Your group</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

authentications/templates/authentications/login.html
{% extends 'task/navigations/base.html' %}

{% load crispy_forms_tags %}
{% block title %} Login Page {% endblock %}


{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h2>Sign in</h2>
            <hr>
            
            <form method="POST" action="{% url 'authentications:loggin' %}">
                
                {% csrf_token %}
                <div class="form-group col-md-10 mx-auto">
                    <div class="text-success mx-auto">
                        {% for msgs in messages %}
                        <span>
                            {{ msgs }}
                        </span>
                        {% endfor %}
                    </div>
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.username|as_crispy_field }}
                    </div>  
    
                </div>
                
                <div class="form-group col-md-10 mx-auto mb-3">
                    
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.password|as_crispy_field }}
                    </div>  
                  
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error:</strong> {{ form.non_field_errors.0 }}
                        </div>
                    {% endif %}
                    
                    <button type="submit" class="btn btn-primary pt-3 px-5">Sign in</button>
                    <p class="">Don't have an account?<a href="{% url 'authentications:register_user' %}">Signup</a> </p>
                    <p class="">Forget Password<a href="">Reset</a> </p>
                </div>
                
                
            </form>
        </div>
    </div>
    
</div>

{% endblock %}

authentications/templates/authentications/personal_user_instruction.html
{% extends 'task/navigations/base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    
<div class="jumbotron text-center pt-5" style="background-color: #f8f9fa;">
    <h1 class="display-0" style="font-family: 'Montserrat', sans-serif; color: #343a40;">Welcome to</h1>
    <h2 class="display-0" style="font-family: 'Pacifico', cursive; color: #2b9e82;">Task Management Systme</h2>
    <p class="lead" style="color: #6c757d;">Add and check your task here</p>
</div>
  
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Welcome to Task Management System</h2>
            <p class="card-text">Are you here for personal use or for your company?</p>
            <div class="row justify-content-center">
                <p>
                    Welcome to the Task Management System! As a personal user, you have access to various features to help you stay organized.
Login to your account using your username and password on the login page.
Once logged in, you will be redirected to your personal user dashboard.
From the dashboard, you can create tasks, add to-do items, and keep track of your schedule.
To create a task, click on the "Create Task" button and provide the necessary details such as task name, description, and due date.
You can also add to-do items by clicking on the "Add To-Do" button and specifying the task, description, and due date for each item.
Use the dashboard to manage and update your tasks and to-dos as needed.
                </p>
                <div class="col-md-6">
                    <a href="{% url 'projectform' %}" class="btn btn-primary btn-block">Create a Todo</a>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'index' %}" class="btn btn-secondary btn-block">View Todo</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

authentications/templates/authentications/personaluser.html
{% extends 'task/navigations/base.html' %}

{% load crispy_forms_tags %}
{% block title %} Sign Page {% endblock %}


{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h2>Sign Up</h2>
            <hr>
            
            <form method="POST" action="{% url 'authentications:personalusers' %}">
                
                {% csrf_token %}
                <div class="form-group col-md-10 mx-auto">
                    <div class="text-success mx-auto">
                        {% for msgs in messages %}
                        <span>
                            {{ msgs }}
                        </span>
                        {% endfor %}
                    </div>
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.username|as_crispy_field }}
                    </div> 
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.email|as_crispy_field }}
                    </div>

    
                </div>
                
                <div class="form-group col-md-10 mx-auto mb-3">
                    
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="col-sm-5 form-control ">
                        {{ form.password2|as_crispy_field }}
                    </div> 
                    <div class="col-sm-5 form-control ">
                        {{ form.reason|as_crispy_field }}
                    </div> 
                  
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error:</strong> {{ form.non_field_errors.0 }}
                        </div>
                    {% endif %}
                    
                    <button type="submit" class="btn btn-primary pt-3 px-5">Sign up</button>
                    <p class="">Have account?<a href="{% url 'authentications:loggin' %}">Sign in</a> </p>
                    <p class="">Forget Password<a href="">Reset</a> </p>
                </div>
                
                
            </form>
        </div>
    </div>
    
</div>

{% endblock %}

authentications/templates/authentications/signup.html
{% extends 'task/navigations/base.html' %}

{% load crispy_forms_tags %}
{% block title %} Sign Page {% endblock %}


{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h2>Sign Up</h2>
            <hr>
            
            <form method="POST" action="{% url 'authentications:register_user' %}">
                
                {% csrf_token %}
                <div class="form-group col-md-10 mx-auto">
                    <div class="text-success mx-auto">
                        {% for msgs in messages %}
                        <span>
                            {{ msgs }}
                        </span>
                        {% endfor %}
                    </div>
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.username|as_crispy_field }}
                    </div> 
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.email|as_crispy_field }}
                    </div>

    
                </div>
                
                <div class="form-group col-md-10 mx-auto mb-3">
                    
                    <label class="col-md-5 col-form-label">{{ form.label }}</label>
                    <div class="col-sm-5 form-control ">
                        {{ form.password1|as_crispy_field }}
                    </div>
                    <div class="col-sm-5 form-control ">
                        {{ form.password2|as_crispy_field }}
                    </div> 
                    <div class="col-sm-2 form-control ">
                        {{ form.is_personal|as_crispy_field }}
                    </div>
                    <div class="col-sm-2 form-control ">
                        {{ form.is_group_leader|as_crispy_field }}
                    </div>
                    <div class="col-sm-2 form-control mb-5 ">
                        {{ form.is_group_member|as_crispy_field }}
                    </div> 
                  
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error:</strong> {{ form.non_field_errors.0 }}
                        </div>
                    {% endif %}
                    
                    <button type="submit" class="btn btn-primary pt-3 px-5">Sign up</button>
                    <p class="">Have account?<a href="{% url 'authentications:loggin' %}">Sign in</a> </p>
                    <p class="mb-5">Forget Password<a href="">Reset</a> </p>
                </div>
                
                
            </form>
        </div>
    </div>
    
</div>

{% endblock %}